options:
  logging: CLOUD_LOGGING_ONLY  # Required for user-managed service accounts

steps:
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/react-app:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/react-app:$COMMIT_SHA'